install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --all --locked

before_deploy:
  - ps: |
        $NAME = "cargo-generate-${env:APPVEYOR_REPO_TAG_NAME}-x86_64-pc-windows-msvc"
        New-Item -Path $NAME -ItemType directory
        Copy-Item target/release/cargo-generate.exe "${NAME}/"
        Copy-Item LICENSE-MIT "${NAME}/"
        Copy-Item LICENSE-APACHE "${NAME}/"
        Copy-Item README.md "${NAME}/"
        7z a -ttar "${NAME}.tar" "${NAME}"
        7z a "${NAME}.tar.gz" "${NAME}.tar"
        Push-AppveyorArtifact "${NAME}.tar.gz"
deploy:
  artifact: /.*\.tar.gz/
  description: 'Appveyor Automated Release'
  provider: GitHub
  draft: false
  prerelease: false
  auth_token:
    secure: iHsRUqwGf/Zh7OuYpHOWQL8buaOL+c8/6kXLRly8V2j0LCUo7CcDs0NxQ0vl2bhZ
  on:
    appveyor_repo_tag: true
