name: Deploy
on:
    push:
        branches:
            - cargo_generate_guide

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup mdBook
                  uses: peaceiris/actions-mdbook@v1
                  with:
                    mdobook-version: 'latest'
            - run: cd guide && mdbook build
              
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              #              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./guide/book

